=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/schemas/room_schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1659519733.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"room_id",
		"name",
		"floor_no"
	],
	"properties": {
		"room_id": {
			"$id": "#root/room_id", 
			"title": "Room_id", 
			"type": "string",
			"default": "",
			"examples": [
				"G-08"
			],
			"pattern": "^.*$"
		},
		"name": {
			"$id": "#root/name", 
			"title": "Name", 
			"type": "string",
			"default": "",
			"examples": [
				"Open Lab - I"
			],
			"pattern": "^.*$"
		},
		"floor_no": {
			"$id": "#root/floor_no", 
			"title": "Floor_no", 
			"type": "string",
			"default": "",
			"examples": [
				"G"
			],
			"pattern": "^.*$"
		},
		"capacity": {
			"$id": "#root/capacity", 
			"title": "Capacity", 
			"type": "string",
			"default": "",
			"examples": [
				"30-40"
			],
			"pattern": "^.*$"
		},
		"area": {
			"$id": "#root/area", 
			"title": "Area", 
			"type": "string",
			"default": "",
			"examples": [
				""
			],
			"pattern": "^.*$"
		},
		"person_in_charge": {
			"$id": "#root/person_in_charge", 
			"title": "Person_in_charge", 
			"type": "string",
			"default": "",
			"examples": [
				""
			],
			"pattern": "^.*$"
		},
		"link": {
			"$id": "#root/link", 
			"title": "Link", 
			"type": "string",
			"default": "",
			"examples": [
				"https://ce.pdn.ac.lk/facilities/open-lab"
			],
			"pattern": "^.*$"
		},
		"features": {
			"$id": "#root/features", 
			"title": "Features", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/features/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"Whiteboards"
				],
				"pattern": "^.*$"
			}
		},
		"accessibility": {
			"$id": "#root/accessibility", 
			"title": "Accessibility", 
			"type": "object",
			"required": [
				"academic_staff",
				"instructors",
				"technical_officers",
				"undergrad_students",
				"postgrad_students",
				"guests"
			],
			"properties": {
				"academic_staff": {
					"$id": "#root/accessibility/academic_staff", 
					"title": "Academic_staff", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"instructors": {
					"$id": "#root/accessibility/instructors", 
					"title": "Instructors", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"technical_officers": {
					"$id": "#root/accessibility/technical_officers", 
					"title": "Technical_officers", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"undergrad_students": {
					"$id": "#root/accessibility/undergrad_students", 
					"title": "Undergrad_students", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"postgrad_students": {
					"$id": "#root/accessibility/postgrad_students", 
					"title": "Postgrad_students", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"guests": {
					"$id": "#root/accessibility/guests", 
					"title": "Guests", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				}
			}
		}
,
		"staff_ids": {
			"$id": "#root/staff_ids", 
			"title": "Staff_ids", 
			"type": "array",
			"default": []
		},
		"additional_notes": {
			"$id": "#root/additional_notes", 
			"title": "Additional_notes", 
			"type": "string",
			"default": "",
			"examples": [
				"To be used by students for group-work, tech talks etc. After hours access through G-11."
			],
			"pattern": "^.*$"
		},
		"tags": {
			"$id": "#root/tags", 
			"title": "Tags", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/tags/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"lab"
				],
				"pattern": "^.*$"
			}
		}
	}
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/fourth_floor/4_08.json
{
    "room_id": "04-08",
    "name": "Computer Laboratory 1",
    "floor_no": "4",
    "capacity": "70",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/main-computer-lab",
    "features": [
        "Multimedia Projector"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/ground_floor/g_07.json
{
    "room_id": "g_07",
    "name": "Staff Common Room",
    "floor_no": "G",
    "capacity": "",
    "area": "",
    "person_in_charge": "",
    "link": "",
    "features": [],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": false,
        "postgrad_students": false,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "To be used for lunch, tea and other informal gatherings.",
    "tags": [
        "staff"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/first_floor/1_00.json
{
    "room_id": "1_00",
    "name": "Computer Laboratory 2",
    "floor_no": "1",
    "capacity": "64",
    "area": "",
    "person_in_charge": "",
    "link": "",
    "features": [
        "2 built in projectors and screens 64 computers"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/ground_floor/g_04.json
{
    "room_id": "g_04",
    "name": "Central Lobby, Library, Museum",
    "floor_no": "G",
    "capacity": "N/A",
    "area": "",
    "person_in_charge": "",
    "link": "",
    "features": [],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": true
    },
    "staff_ids": [],
    "additional_notes": "This is a transit area",
    "tags": [
        "public"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/third_floor/3_08.json
{
    "room_id": "3_08",
    "name": "ESCAL Makerspace Lab",
    "floor_no": "3",
    "capacity": "20",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/makerspace",
    "features": [
        "5 Working Stations",
        "Fabrication facilities"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/first_floor/1_09.json
{
    "room_id": "1_09",
    "name": "Network and Communication Laboratory",
    "floor_no": "1",
    "capacity": "30",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/networking-lab",
    "features": [
        "Computers", 
        "Networking Devices"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "To be used for Networking related courses.",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/ground_floor/g_03.json
{
    "room_id": "g_03",
    "name": "Conference Room",
    "floor_no": "G",
    "capacity": "15",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/conference-room/",
    "features": [
        "Smart Display",
        "Conference Camera",
        "Conference Mic"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": true
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "public"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/second_floor/2_00.json
{
    "room_id": "2_00",
    "name": "Hardware and Computer Interfacing Lab",
    "floor_no": "2",
    "capacity": "60",
    "area": "",
    "person_in_charge": "Mr. Kelum Gunarathne",
    "link": "https://ce.pdn.ac.lk/facilities/hardware-and-interfacing-lab/",
    "features": [
        "30 Computers", 
        "Oscilloscopes",
        "Power Supplies", 
        "Signal Generators"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": false,
        "postgrad_students": false,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "To be used for Digital Design, Embedded Systems and other courses.",
    "tags": [
        "lab"
    ]
}
