=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/schemas/room_schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1659519733.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"room_id",
		"name",
		"floor_no"
	],
	"properties": {
		"room_id": {
			"$id": "#root/room_id", 
			"title": "Room_id", 
			"type": "string",
			"default": "",
			"examples": [
				"G-08"
			],
			"pattern": "^.*$"
		},
		"name": {
			"$id": "#root/name", 
			"title": "Name", 
			"type": "string",
			"default": "",
			"examples": [
				"Open Lab - I"
			],
			"pattern": "^.*$"
		},
		"floor_no": {
			"$id": "#root/floor_no", 
			"title": "Floor_no", 
			"type": "string",
			"default": "",
			"examples": [
				"G"
			],
			"pattern": "^.*$"
		},
		"capacity": {
			"$id": "#root/capacity", 
			"title": "Capacity", 
			"type": "string",
			"default": "",
			"examples": [
				"30-40"
			],
			"pattern": "^.*$"
		},
		"area": {
			"$id": "#root/area", 
			"title": "Area", 
			"type": "string",
			"default": "",
			"examples": [
				""
			],
			"pattern": "^.*$"
		},
		"person_in_charge": {
			"$id": "#root/person_in_charge", 
			"title": "Person_in_charge", 
			"type": "string",
			"default": "",
			"examples": [
				""
			],
			"pattern": "^.*$"
		},
		"link": {
			"$id": "#root/link", 
			"title": "Link", 
			"type": "string",
			"default": "",
			"examples": [
				"https://ce.pdn.ac.lk/facilities/open-lab"
			],
			"pattern": "^.*$"
		},
		"features": {
			"$id": "#root/features", 
			"title": "Features", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/features/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"Whiteboards"
				],
				"pattern": "^.*$"
			}
		},
		"accessibility": {
			"$id": "#root/accessibility", 
			"title": "Accessibility", 
			"type": "object",
			"required": [
				"academic_staff",
				"instructors",
				"technical_officers",
				"undergrad_students",
				"postgrad_students",
				"guests"
			],
			"properties": {
				"academic_staff": {
					"$id": "#root/accessibility/academic_staff", 
					"title": "Academic_staff", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"instructors": {
					"$id": "#root/accessibility/instructors", 
					"title": "Instructors", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"technical_officers": {
					"$id": "#root/accessibility/technical_officers", 
					"title": "Technical_officers", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"undergrad_students": {
					"$id": "#root/accessibility/undergrad_students", 
					"title": "Undergrad_students", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"postgrad_students": {
					"$id": "#root/accessibility/postgrad_students", 
					"title": "Postgrad_students", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				},
				"guests": {
					"$id": "#root/accessibility/guests", 
					"title": "Guests", 
					"type": "boolean",
					"examples": [
						true
					],
					"default": true
				}
			}
		}
,
		"staff_ids": {
			"$id": "#root/staff_ids", 
			"title": "Staff_ids", 
			"type": "array",
			"default": []
		},
		"additional_notes": {
			"$id": "#root/additional_notes", 
			"title": "Additional_notes", 
			"type": "string",
			"default": "",
			"examples": [
				"To be used by students for group-work, tech talks etc. After hours access through G-11."
			],
			"pattern": "^.*$"
		},
		"tags": {
			"$id": "#root/tags", 
			"title": "Tags", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/tags/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"lab"
				],
				"pattern": "^.*$"
			}
		}
	}
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/ground_floor/G08.json
{
    "room_id": "G-08",
    "name": "Open Lab",
    "floor_no": "G",
    "capacity": "30-40 students",
    "area": "100 sq. ft.",
    "person_in_charge": "Mr.ABC",
    "link": "",
    "features": [
        "whiteboards",
        "facilities for using laptops"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": true
    },
    "staff_ids": [
        "ABCr",
        "XYZj"
    ],
    "additional_notes": "To be used by students for group-work, tech talks, etc.. After Hours access through G-11 .",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/ground_floor/g_11.json
{
    "room_id": "g_11",
    "name": "Open Lab Entrance Lobby",
    "floor_no": "G",
    "capacity": "N/A",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/open-lab",
    "features": [
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": true
    },
    "staff_ids": [],
    "additional_notes": "Providing after hours access to G-08 and G-09",
    "tags": [
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/ground_floor/g_08.json
{
    "room_id": "G_08",
    "name": "Open Lab - I",
    "floor_no": "G",
    "capacity": "30-40",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/open-lab",
    "features": [
        "Whiteboards",
        "Facilities for using laptops"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": true
    },
    "staff_ids": [],
    "additional_notes": "To be used by students for group-work, tech talks etc. After hours access through G-11.",
    "tags": [
        "lab",
        "public"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/Groud_floor/G08.json
{
    "room_id": "G-08",
    "name": "Open Lab",
    "floor_no": "Ground",
    "capacity": "30-40 students",
    "person_in_charge": "Mr.ABC",
    "features": [
        "whiteboards",
        "facilities for using laptops"
    ],
    "staff_ids": [
        "ABCr",
        "XYZj"
    ],
    "additional_notes": "To be used by students for group-work, tech talks, etc.. After Hours access through G-11 .",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/third_floor/3_07.json
{
    "room_id": "3_07",
    "name": "Technical Officer's Room",
    "floor_no": "3",
    "capacity": "3",
    "area": "",
    "person_in_charge": "Mr. Wasundara",
    "link": "",
    "features": [
        "Additionally used as material storage"
    ],
    "accessibility": {
        "academic_staff": false,
        "instructors": false,
        "technical_officers": true,
        "undergrad_students": false,
        "postgrad_students": false,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        ""
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/first_floor/1_01.json
{
    "room_id": "1_01",
    "name": "Technical Officer's Room",
    "floor_no": "1",
    "capacity": "2",
    "area": "",
    "person_in_charge": "",
    "link": "",
    "features": [],
    "accessibility": {
        "academic_staff": false,
        "instructors": false,
        "technical_officers": true,
        "undergrad_students": false,
        "postgrad_students": false,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "staff"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/third_floor/3_10.json
{
    "room_id": "3_10",
    "name": "ESCAL Robotics Lab",
    "floor_no": "3",
    "capacity": "12",
    "area": "",
    "person_in_charge": "",
    "link": "https://ce.pdn.ac.lk/facilities/robotics-lab",
    "features": [
        "Robotics related works"
    ],
    "accessibility": {
        "academic_staff": true,
        "instructors": true,
        "technical_officers": true,
        "undergrad_students": true,
        "postgrad_students": true,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "lab"
    ]
}

=== cepdnaclk/e18-co227-Augmented-Reality-Guidance-System/assets/data/third_floor/3_06.json
{
    "room_id": "3_06",
    "name": "Instructors and PG Students' Room",
    "floor_no": "3",
    "capacity": "6",
    "area": "",
    "person_in_charge": "",
    "link": "",
    "features": [
        "Working space and storage"
    ],
    "accessibility": {
        "academic_staff": false,
        "instructors": true,
        "technical_officers": false,
        "undergrad_students": false,
        "postgrad_students": true,
        "guests": false
    },
    "staff_ids": [],
    "additional_notes": "",
    "tags": [
        "staff"
    ]
}
